name: build-push-container-image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  version: 0.6
  repository: romeokienzler

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PASSWORD }}
 
    - name: Build the Docker image
      run: |
         cd ./component-library/anomaly/
         ./anomaly-score-unsupervised/build.sh

 

